CREATE TABLE [dbo].[UserList]
(
    [PATIENT_ID] NCHAR(10) NOT NULL, 
    [PassHash] NCHAR(64) NOT NULL, 
    [UserName] NVARCHAR(32) NULL, 
    CONSTRAINT [uName_to_PID] FOREIGN KEY ([PATIENT_ID]) REFERENCES [dbo].[PATIENT_TBL] ([PATIENT_ID]), 
    CONSTRAINT [PK_UserList] PRIMARY KEY ([PATIENT_ID])
)